name: Build Flask App

on:
  push:
    branches: [develop]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11


      - name: Create virtual env
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Test with pytest
        run: |
            pip install pytest pytest-cov
            pytest test.py 

      - name: Set up SSH key and whitelist EC2 IP address
        run: |
          mkdir -p ~/.ssh
          echo """-----BEGIN RSA PRIVATE KEY-----
          MIIEpQIBAAKCAQEAhKxx576Pzc+DFzzO0CGegEWQCNSdSGTyvkvVdoW+G9Kgh6b7
          t8aHmzpAdxWWhzT65NubyQvENvDf/gYo0/g/fTpehPygSOADudEr9UemmrPjWp3v
          Xa7OaNhfdpydnQqkXSRS2yLajuHdE8gGJf5/DiWbRfcUOX8b7N6xW+5bZ8Ph510i
          Y7UfqtZhaHuxcXp4UWKPKQpHTB6Po7wL9bmNi4QFeR05oRJ05bWb8GVs82E8JNXh
          ZGhtkFrPxLu6H4nYkeUpQBuPipvMmTVS2brmSMwFlfTWWNzW7Fb+1bC80s/tHV3u
          83muzR86cc9TETAKC6Nj2dRZoSGoNnLOWnx3nQIDAQABAoIBAGlIBqOl3qutbhN0
          l5El/IdBrEi1n5IhOVe1CdGh0/h0Lhs3cSymiFmv4hQdt3PXoPkXJApoIe6POtBz
          xtZeetM/DF5vsiniSlKcIEvl7dl5woLYLWikHPuqKCcRpSlHlqKq/m0SvWkA5tSZ
          t/dSezSYtxzQMuZlbZ2MIiYXgcVW0RVgrlJnD9DIr2XIpMRkTWuY27oYH6T5hby1
          MXg//U8sRNjKmJMX9bQ27N7nVueqBI8JtGj1iaQ0QAMe3WKi5I/n+dntD6kI2Iu4
          95GJXGTC6teO7OoEtaMDXepGgxYuglxosg+jQ1+/ysP0EJ+TffmiYZq964TstGWS
          oQLx/qkCgYEAwMLHJ9wV4xkb5p97LG3S5GL/TkwfeTXNvvSSGeRlBPbDzOhDH3Yk
          4Si3rOo5sPPCMPousF7IsJeGSsekrMAcrMOdkDw2SuzUXnr7Jk3/yD9dm97kuq1A
          kRofxwpTRdS3aaOlzSTF+Ys1kBBZ8B9gutDtLuW6KcrVdsYy5VHWmOcCgYEAsDMt
          ZYAafDzcpppgNd/7GBTUxQ6ioerBbcexbAfQD6YjpUyAMNegb/15REhlsWP3jJqM
          3l6pnp7+sclcKWnwhvyE4ldlguK2GuAqqWhfdecsjT5QnsMQKP8OCBtdFYD3sozB
          G8BISLiUMEYxj7OoWt7WFrlKXfn+m52ZwMeTxtsCgYEAs6zbNqxPOoANIctGZQN5
          sKkWkUUjkTg1r+kIxlm+UAI0QKu+5XSaq8Xob6VkYSzVthF9s6imKPUUmF+/f8cS
          83bjR67YbL6UtfysXegWo/Fsr/3z9o3HwXk4Za+aL104GaAQzEeawiCgrMiRDOIy
          p/BXJX+9J3eJwky85ESEY8ECgYEArYnKJVTVQRWkcIZNSeKO6Hnj0S2H6hdPaTMr
          wG21cyQ7qVs+SlylDIfGfwUa+2qs7pNtOLpdLvgDe9EJb1SC7EAbFN3lAdMObkvo
          WK+OjY4g5/++4Y7XBLmn9T4WIM7DptxQeWeZCd6ZPS51M8ZLgyxECV93KjXFmTjQ
          rPkjx88CgYEArLSiLy86qbI+sLeJdp+N+9JA8yWVUN8nsCZoDFPNscw+jOD4FD2g
          ZktXJpZMm0g77qa6qy3Zml01HodyNaTHucR6lbmsSw8Rf2CaP7ayEcMyk78GZBxO
          V5+0noT8V0tphtCiVa30jg7bYOfsql0Qt0fgnsbZEzxHWQhLXkLM4hU=
          -----END RSA PRIVATE KEY-----""" > ~/.ssh/id_rsa

          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 15.188.50.221 >> ~/.ssh/known_hosts
      - name: Copy the main script to remote server
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        run: |
          scp -r deploy.sh ubuntu@15.188.50.221:/home/ubuntu/
      - name: Deploying in EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          PROJECT_HOME_DIR: ${{ secrets.PROJECT_HOME_DIR }}
          SERVICE_NAME: ${{ secrets.SERVICE_NAME }}

        run: |
          ssh -o StrictHostKeyChecking=no  ubuntu@15.188.50.221 "chmod +x ./deploy.sh && ./deploy.sh"
            
            
            

