name: Build Flask App

on:
  push:
    branches: [develop]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11


      - name: Create virtual env
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Test with pytest
        run: |
            pip install pytest pytest-cov
            pytest test.py 

      - name: Set up SSH key and whitelist EC2 IP address
        run: |
          mkdir -p ~/.ssh
          echo """-----BEGIN RSA PRIVATE KEY-----
          MIIEpAIBAAKCAQEAsF3RHtoCsXFVFcg0JSS9iQ5jaL/B1OsbISV2Zbopx1NtZaPm
          hCpvphnRVFLaRD53/tviLOU5mY3Wd9I966pvjEOoSZLh1tGIZbZ8xSS6bGbwgVyV
          bgv78YiMG+y57t0rkDHH/AgqM+zsVyBZDv3OywagtZzPu44aoYDo4mEU/KKskYm+
          yteC0z0jIoROyjVEgjEPPmXrzZeNOtLoKRBiG/iP/B+nlkc55SIL/4IWZl1XUW0U
          M77bDt5z0hmQ/eHlObssaXlPtv/Tv0BFyDnDYpjevff/jSNg4KM2tv3KYolPEYvh
          0v1NBsHhmOruW320TNM89rHtHPLKboiFYXDRswIDAQABAoIBAQCGehKBFrRk/khl
          QnFYPQp0Hc94yHYQVnAqNvlvGaLPhHJuxKl47y6QlTECveYFkShH4Ps1RldEGV2F
          oX5rWlqRtej0qJWhCcWZ4KqEW7v1+gu6Z5DdBzBE+9vxUvB3DJcx7HNTXhpn22he
          CqE9iBOMxPH3aKkQlosByFxKeMHa2xvboRAg7NfruMEbsE3cZV01syDl4+5FDZS1
          7bXm6czrSd9b99qtGfMMyZfMlqTC7CvPHI9V+jcDG0mK8TFnqsiQaIo7RxJNE0DG
          nXQNj7pQ327D0rKJ1zRHrDuOLSBf97ve/Fvah6nbKO80RoIuOH3adJHavHJFNZJd
          xaMkjLXxAoGBAPQA/Gf/KKxPXQhWXEemvjYS4foBYF7EpJYBlrMA8mqzWF3pQUN5
          akyrBrwg1afUFbdY5GD99zZFDq4g0AKj2Dxa4/FzUM9c/lXYSByHYmby/80A8bbw
          8Cq/NoDfhEjrQo5Fy4BaERyFJ3dHRQfeVf2bxmaykY05ZBQoy3jm5n3JAoGBALkJ
          jU3u1kE/1XHUUfzBfLGUo2YdV5RA2LohKQHzDLp/AQQ1ZC3lhX389fJ41O1d/r3j
          NdVsdFq/3xtp/ga8tIexcMCTH98PKAhd13UyNg9RF4gdEqDN8gaxRmo5e9wGMkxD
          3l3HfbCsdTnNpqqc7KKZfhgTAYDl4QUTy2tLLeGbAoGAYT+jWa+QflyDL7d7v/Lt
          DJAqEIJL7nlhP4gSj/VoqK4iIgu9Py889qGTZZeQj/svTIvZOe7+gFq1pyDcxrCW
          ljeDcdAL/RmLJJu24efziCSBXytpKwiML/1Vs7dh+c4KELowiU9cUomfWSLGmIQ8
          sX9Ma9HvwOGGyaIYtm8QnkECgYEAr/xIu5Vri3Vl0TRpoeZ4bQD8g3Nmx2cBec1u
          Dh+WvI1sbw9Er247j38WgD2x7exXC0zc95aF94XDcXRWmRvC68e0gEOtrV3h6ksu
          T5Wo2tp6cgeMnwogpYLXgNIZXkM6dVSbWkAQ6AauG4LfgCdt3Jv11HnHFUwNvuF7
          uBkxkv8CgYBuTX7gWsc3XfCtKTBbbA7y5vVsNLAaTNV5d1oH46wf3ZpMBRij42AU
          yT9FLuiUnUvTfOYQewAi10TGqHaXJ0CNyKFpLViWUzxjcsHgm+f7aVfruZmRXaPT
          9JCNiMx8nkbsRwrCudsa6AGluusQULxlJOkSSMf5sf0Jx2KND+w4wQ==
          -----END RSA PRIVATE KEY-----""" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 35.181.24.149 >> ~/.ssh/known_hosts

      - name: Copy the main script to remote server
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        run: |
          scp -r deploy.sh ubuntu@35.181.24.149 :/home/ubuntu/

      - name: Deploying in EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          PROJECT_HOME_DIR: ${{ secrets.PROJECT_HOME_DIR }}
          SERVICE_NAME: ${{ secrets.SERVICE_NAME }}

        run: |
          ssh -o StrictHostKeyChecking=no  ubuntu@35.181.24.149  "chmod +x ./deploy.sh && ./deploy.sh"
            
            
            

