name: Scoring CI

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Export environment variable
        run: |
           FLASK_APP=backend.py
           FLASK_ENV=development
           FLASK_DEBUG=0
           echo "FLASK_APP=$FLASK_APP" >> $GITHUB_ENV
           echo "FLASK_ENV=$FLASK_ENV" >> $GITHUB_ENV
           echo "FLASK_DEBUG=$FLASK_DEBUG" >> $GITHUB_ENV

#      - name: Print debugging information
#        run: |
#          echo "Python Version: $(python --version)"
#          echo "Working Directory: $(pwd)"
#          echo "Contents of Working Directory: $(ls -l)"
#          echo "Contents of site-packages: $(ls -l venv/lib/python*/site-packages)"
#          echo "Flask App name: ${{env.FLASK_APP}}"
#          echo "Flask Env name: ${{env.FLASK_ENV}}"
#          echo "Flask Debug: ${{env.FLASK_DEBUG}}"

#      - name: Run streamlit App
#        run: streamlit run web.py

#      - name: Run Backend Flask App
#        run: flask run